language: go
sudo: false 

go:
- "1.11"
- master

matrix:
  allow_failures:
  - go: master
  fast_finish: true

install:
  - true

script: 
- ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
